spring:
  datasource:
    url: jdbc:postgresql://dpg-d2p10vl6ubrc73875l10-a.oregon-postgres.render.com:5432/livechat_bjpo
    username: livechat
    password: Y5cQyWBCWhA0wJbSxHImkDklLWOc14Gd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: DFmjevhaecniwefCjMJNEUNHFEXJINCWEHNFUNHSKJDASFKJHJDmjrcnhrukgafm
  expiration-ms: 3600000 # 1 hour in milliseconds